import type { Tool } from "./DomeGallery";

export const TOOLS: Tool[] = [
  { name: "Python", mark: "Py", category: "Languages", accent: "#3776ab", description: "The main language I use to build, test, and connect data systems." },
  { name: "SQL", mark: "SQL", category: "Languages", accent: "#e58a13", description: "For querying the data layer and turning raw tables into useful answers." },
  { name: "scikit-learn", mark: "sk", category: "ML / AI", accent: "#f7931e", description: "A reliable base for classical models, pipelines, and evaluation." },
  { name: "TensorFlow", mark: "Tf", category: "ML / AI", accent: "#ff6f00", description: "Used when a project needs trainable neural networks at scale." },
  { name: "Keras", mark: "K", category: "ML / AI", accent: "#d00000", description: "A clear, fast way to prototype and explain deep-learning models." },
  { name: "XGBoost", mark: "XG", category: "ML / AI", accent: "#1261a0", description: "A strong choice for structured data and high-signal tabular predictions." },
  { name: "LightGBM", mark: "LGB", category: "ML / AI", accent: "#5a9b54", description: "Fast gradient boosting for large, practical tabular datasets." },
  { name: "Embeddings", mark: "Em", category: "LLMs", accent: "#7c4dff", description: "The representation layer behind semantic search and matching systems." },
  { name: "RAG", mark: "RAG", category: "LLMs", accent: "#ec407a", description: "A way to ground language-model answers in relevant source material." },
  { name: "ChromaDB", mark: "C", category: "LLMs", accent: "#f5a623", description: "A lightweight vector store for retrieval experiments and prototypes." },
  { name: "FastAPI", mark: "FA", category: "Engineering", accent: "#009688", description: "The API layer I reach for when a model needs a clean interface." },
  { name: "Pandas", mark: "pd", category: "Data", accent: "#150458", description: "For cleaning, joining, reshaping, and understanding datasets." },
  { name: "NumPy", mark: "Np", category: "Data", accent: "#4dabcf", description: "The numerical foundation for arrays, transforms, and scientific work." },
  { name: "Matplotlib", mark: "Mpl", category: "Data", accent: "#11557c", description: "For precise plots that make model behavior and data patterns legible." },
  { name: "Plotly", mark: "Pl", category: "Data", accent: "#3f4f75", description: "For interactive visual stories, dashboards, and exploratory analysis." },
  {"name": "Feature engineering", "mark": "FE", "category": "ML / AI", "accent": "#5a9b54", "description": "Designing useful predictors and selecting features that generalize."},
  {"name": "Model evaluation", "mark": "Eval", "category": "ML / AI", "accent": "#5a9b54", "description": "Comparing metrics and validation splits, with checks for data leakage."},
  {"name": "Hyperparameter tuning", "mark": "HPO", "category": "ML / AI", "accent": "#5a9b54", "description": "Optimizing model settings while tracking validation performance."},
  {"name": "Supervised learning", "mark": "SL", "category": "ML / AI", "accent": "#5a9b54", "description": "Classification and regression models trained on labelled examples."},
  {"name": "Ensemble learning", "mark": "Ens", "category": "ML / AI", "accent": "#5a9b54", "description": "Combining models through averaging, blending and stacking."},
  {"name": "Deep learning / CNNs", "mark": "CNN", "category": "ML / AI", "accent": "#5a9b54", "description": "Neural networks and convolutional architectures for learning representations."},
  {"name": "Classical NLP", "mark": "NLP", "category": "ML / AI", "accent": "#5a9b54", "description": "Text preprocessing, tokenization and statistical representations."},
  {"name": "OCR", "mark": "OCR", "category": "ML / AI", "accent": "#5a9b54", "description": "Extracting text from images and scanned documents."},
  {"name": "MySQL", "mark": "My", "category": "Data", "accent": "#4dabcf", "description": "Relational tables and queries for structured application data."},
  {"name": "Google BigQuery", "mark": "BQ", "category": "Data", "accent": "#4dabcf", "description": "SQL-based analysis of large datasets in a cloud data warehouse."},
  {"name": "Data pipelines", "mark": "ETL", "category": "Data", "accent": "#4dabcf", "description": "Moving, cleaning and transforming data into reusable datasets."},
  {"name": "Data management", "mark": "DM", "category": "Data", "accent": "#4dabcf", "description": "Organizing datasets and maintaining quality and consistency."},
  {"name": "Exploratory analysis", "mark": "EDA", "category": "Data", "accent": "#4dabcf", "description": "Exploring patterns through descriptive and diagnostic analysis."},
  {"name": "Predictive analysis", "mark": "Pred", "category": "Data", "accent": "#4dabcf", "description": "Using historical data and models to estimate outcomes."},
  {"name": "Data visualization", "mark": "Viz", "category": "Data", "accent": "#4dabcf", "description": "Communicating patterns and model behavior through charts."},
  {"name": "PySide / GUI development", "mark": "Qt", "category": "Engineering", "accent": "#009688", "description": "Building desktop interfaces around Python tools."},
  {"name": "Figma", "mark": "Fig", "category": "Engineering", "accent": "#009688", "description": "Planning interface layouts and exploring visual design."},
  {"name": "Automation", "mark": "Auto", "category": "Engineering", "accent": "#009688", "description": "Turning repetitive tasks into scripted workflows."},
  {"name": "Performance tuning", "mark": "Perf", "category": "Engineering", "accent": "#009688", "description": "Finding bottlenecks and improving resource use."},
  {"name": "MLOps basics", "mark": "Ops", "category": "Engineering", "accent": "#009688", "description": "Foundations of reproducible artifacts, inference services and deployment checks."},
];
